# Generated by Django 3.0.2 on 2020-02-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
